---
- name: Update Cache
  apt:
    update_chache: yes
  changed_when: false

- name: Install redis-server
  apt:
    name: redis-server

- name: Copy Redis conf 
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: 0600
